# Generated by Django 2.2.11 on 2020-03-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hghg', models.BigIntegerField()),
            ],
        ),
    ]
